apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cci-pipeline
spec:
  workspaces:
    - name: myworkspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: myworkspace
      params:
        - name: url
          value: {YOUR_GIT_REPOSITORY_URL}
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      params:
        - name: IMAGE
          value: docker.io/{YOUR_DOCKERHUB_REPOSITORY_NAME}
        - name: IMAGE_PUSH_SECRET_NAME
          value: image-push-secrets
      workspaces:
        - name: source
          workspace: myworkspace
