kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sample-backend-api-sample-api-1
  namespace: cci
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: sample-backend-api-sample-api-1
    weight: 100
  port:
    targetPort: 3000
  wildcardPolicy: None
