kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: cci
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Release.Name }}
    weight: 100
  port:
    targetPort: 3000
  wildcardPolicy: None
