apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}'
spec:
  selector:
    app: sample-api-1
    app/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
